DROP TABLE REGISTRATION;

CREATE TABLE REGISTRATION
(
	NUMBER			  	INT(100) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME             	VARCHAR(500)  	  NULL,
	ATTENDANCE			VARCHAR(500)      NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

COMMIT;